plugins {
    id 'org.springframework.boot' version '3.2.9' apply false
    id 'io.spring.dependency-management' version '1.1.5' apply false
    id 'com.google.protobuf' version '0.9.4' apply false
}

ext {
    javaVersion = JavaVersion.VERSION_17
    protobufVersion = '3.25.1'
    grpcVersion = '1.61.0'
    curatorVersion = '5.6.0'
    pactVersion = '4.6.17'
    pactPluginDriverVersion = '0.5.1'
}

subprojects {
    apply plugin: 'java'

    group = 'ru.mipt.software2'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    java {
        sourceCompatibility = javaVersion
        targetCompatibility = javaVersion
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

