startDelaySeconds: 0
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: 'java.lang<type=Memory><HeapMemoryUsage>(used|committed|max):'
    name: jvm_memory_heap_$1_bytes
    type: GAUGE
  - pattern: 'java.lang<type=Memory><NonHeapMemoryUsage>(used|committed|max):'
    name: jvm_memory_nonheap_$1_bytes
    type: GAUGE
  - pattern: 'java.lang<type=GarbageCollector,name=(.+)><>CollectionCount'
    name: jvm_gc_collection_count_total
    type: COUNTER
    labels:
      collector: "$1"
  - pattern: 'java.lang<type=GarbageCollector,name=(.+)><>CollectionTime'
    name: jvm_gc_collection_time_milliseconds_total
    type: COUNTER
    labels:
      collector: "$1"
  - pattern: 'java.lang<type=Threading><>ThreadCount'
    name: jvm_threads_live
    type: GAUGE
  - pattern: 'java.lang<type=OperatingSystem><>(ProcessCpuLoad|SystemCpuLoad)'
    name: jvm_os_$1
    type: GAUGE
  - pattern: 'org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+),name1=replica\\.(\\d+),name2=(.+)><>(PacketsReceived|PacketsSent)'
    name: zookeeper_$4_total
    type: COUNTER
    labels:
      zk_server_id: "$1"
      zk_replica_id: "$2"
      instance: "$3"
